### ISSUE TITLE
Ensure interoperability with "DateTime" and "DateTimeImmutable"

### ISSUE THREAD

**Issue by ocram** [delight-im/PHP-Temporal#1]
* `fromDateTimeInstance`
 * `fromDateTimeImmutableInstance`
 * `toDateTimeInstance`
 * `toDateTimeImmutableInstance`

**Comment by nyamsprod** [comment]
@ocram since `DateTime` and `DateTimeImmutable` shares the same interface `DateTimeInterface` you should only provide on named constructor `fromDateTimeInterfaceInstance`

**Comment by ocram** [comment]
@nyamsprod You're right, of course. Thanks!

 * `fromDateTimeInterface`
 * `toDateTime`
 * `toDateTimeImmutable`

**Comment by ocram** [comment]
Implemented in https://github.com/delight-im/PHP-Temporal/commit/a32148d3e353d0428d235ef264b734cce73d03e3
